[project]
name = "gpt-from-zero"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.0",
    "matplotlib>=3.7.1",
    "numpy>=1.26",
    "pandas>=2.2.1",
    "psutil>=5.9.5",
    "scikit-learn>=1.8.0",
    "tensorflow>=2.16.2 ; platform_machine == 'x86_64' and sys_platform == 'darwin'",
    "tensorflow>=2.18.0 ; platform_machine != 'x86_64' or sys_platform != 'darwin'",
    "tiktoken>=0.5.1",
    "torch>=2.2.2 ; platform_machine != 'x86_64' or sys_platform != 'darwin'",
    "torch>=2.2.2,<2.6 ; platform_machine == 'x86_64' and sys_platform == 'darwin'",
    "torchvision>=0.20.1",
    "tqdm>=4.66.1",
]
